### ISSUE TITLE
Train GANs for low-illuminance dataset

### ISSUE THREAD

**Issue by Teja10** [Michellelind/NVSLAM#4]
Train the initial model on 10 images and make sure its able to overfit.

Found 2-3 image enhancement models. Generating dataset using found models.

**Comment by henrrydegee** [comment]
- Review between low-light enhancing models 
- Test with dark & bright pictures on the models to see if it works (inference)
- Deliverable: Show a good performance of enhancing from dark to bright
- Future Work: Feed Dark-KITTI Datasets into the model

**Comment by andresalxortiz** [comment]
Implemented a working CNN model that illuminates our manually darkened images as well bright images. It is able to improve contrast for the best vision.
 
![004400illuminated](https://user-images.githubusercontent.com/38672289/105622826-85d3ec00-5dc9-11eb-916e-9e2bec68fc40.png)
![004440illuminated](https://user-images.githubusercontent.com/38672289/105622829-88364600-5dc9-11eb-9d4f-3a01a823d1e4.png)
![004490illuminated](https://user-images.githubusercontent.com/38672289/105622957-9fc1fe80-5dca-11eb-854e-c3ca27b71893.png)
